// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAYHi0PAVBJNgIpIgT--b3LiYNOA_rk60',
    appId: '1:216005451863:web:96d06a26b18ab88c100312',
    messagingSenderId: '216005451863',
    projectId: 'gymapp-17b9a',
    authDomain: 'gymapp-17b9a.firebaseapp.com',
    storageBucket: 'gymapp-17b9a.appspot.com',
    measurementId: 'G-HNPNSX86JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIYMirkpbnh2MJmQQ-jTjbXfTYNmBaFA',
    appId: '1:216005451863:android:b00ee2c72de2d5e2100312',
    messagingSenderId: '216005451863',
    projectId: 'gymapp-17b9a',
    storageBucket: 'gymapp-17b9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOy8ssoQwxtzxEe_SheSU0MvxXqIEMJ-A',
    appId: '1:216005451863:ios:29ae909921d450e1100312',
    messagingSenderId: '216005451863',
    projectId: 'gymapp-17b9a',
    storageBucket: 'gymapp-17b9a.appspot.com',
    iosClientId: '216005451863-oi0fr4bj5vftkan3m53ojgabjvupuvt4.apps.googleusercontent.com',
    iosBundleId: 'com.rafael.flutterGymapp',
  );
}
